name: Fill in the Scaffold Placeholders

on:
  repository_dispatch:
    types: [ fill_scaffold ]
  workflow_dispatch:

jobs:
  fill-scaffold:
    if: github.repository != 'georgestephanis/theme-repo-template' # Do not run this on the scaffold itself.

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup proper Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Set github actions[bot] as the committer.
        run: git config --local user.name 'github-actions[bot]' && git config --local user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Rearrange some directories.
        run: |
          git mv --force README.scaffold.md README.md

      - name: Commit the changed files.
        run: git commit -am "chore -- rename files from scaffolding"

      - name: Perform string replacements within the files.
        run: node ./.github/workflows/fill-in-scaffold.mjs '${{ toJSON( github.event.repository ) }}'

      - name: Delete and regenerate package-lock.json.
        run: |
          rm -f package-lock.json
          npm install
          npm run build

      - name: Commit the changed files.
        run: git commit -am "chore -- fill in scaffolding placeholders"

      - name: Clear out this fill-in-scaffold action (as it won‘t need to run again)
        run: |
          rm -f .github/workflows/fill-in-scaffold.yml
          rm -f .github/workflows/fill-in-scaffold.mjs
          git add .github/workflows
          git commit -m "chore -- clear scaffold action"

      - name: Push all the changed files.
        run: git push
